config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'
  resources :bookings, only: [:create]
  get '/confirmation', to: 'bookings#confirmation'
  post '/find_pro_for_existing_booking', to: 'bookings#find_pro_for_existing_booking', as: 'find_pro_bookings'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :professional
  has_one :booking
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :prestation
  belongs_to :professional, optional: true
end

app/models/opening_hour.rb
class OpeningHour < ApplicationRecord
  belongs_to :professional

  validates :day, presence: true
  validates :open_at, presence: true
  validates :close_at, presence: true
end

app/models/prestation.rb
class Prestation < ApplicationRecord
  has_many :services
  has_many :professionals, through: :services
  belongs_to :bookings, optional: true
end

app/models/professional.rb
class Professional < ApplicationRecord
  has_many :bookings
  has_many :services
  has_many :prestations, through: :services
  has_many :appointments, dependent: :destroy
  has_many :opening_hours, dependent: :destroy
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :professional
  belongs_to :prestation
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def create
    @booking = Booking.new(booking_params)
    @booking.user = User.first
    @prestation = Prestation.find_by(id: params['booking']['prestation_id'])

    if @prestation.nil?
      flash[:alert] = 'Prestation not found.'
      redirect_to home_index_path and return
    end

    # Geocode the address
    if @booking.address_of_prestation.present?
      coordinates = Geocoder.coordinates(@booking.address_of_prestation)
      if coordinates
        @booking.lat, @booking.lng = coordinates
      else
        flash[:alert] = 'Geocoding failed, please check the address.'
        render 'home/index' and return
      end
    end

    @nearest_professionals = find_closest_professionals(@booking.lat, @booking.lng) if @booking.lat && @booking.lng

    if @booking.save
      redirect_to confirmation_path(nearest_professionals: @nearest_professionals || [])
    else
      flash[:alert] = 'Booking was NOT created.'
      render 'home/index'
    end
  end

  def find_pro_for_existing_booking
    booking_id = params[:booking][:booking_id]
    booking = Booking.find(booking_id)
    @prestation = booking.prestation

    @nearest_professionals = find_closest_professionals(booking.lat, booking.lng)

    redirect_to confirmation_path(nearest_professionals: @nearest_professionals)
  end

  def confirmation
    if params[:nearest_professionals].blank?
      @selected_professionals = nil
      flash[:notice] = 'No nearest professionals found.'
    else
      @selected_professionals = Professional.where(id: params[:nearest_professionals])
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:prestation_id, :address_of_prestation, :lat, :lng)
  end

  def find_closest_professionals(booking_lat, booking_lng)
    return [] unless @prestation

    professionals = @prestation.professionals.select do |professional|
      distance = Geocoder::Calculations.distance_between([professional.latitude, professional.longitude],
                                                         [booking_lat, booking_lng], units: :km)
      distance <= professional.max_kil  # Only select professionals within range
    end

    professionals.map(&:id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_prestations, only: [:index]
  before_action :set_existing_bookings, only: [:index]

  def index
  end

  def set_prestations
    @prestations = Prestation.all
  end

  def set_existing_bookings
    @existing_bookings = Booking.where(professional_id: nil).pluck(:id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/booking_helper.rb
module BookingHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/bookings/confirmation.html.erb
<h1>Booking Confirmation</h1>
<p>Your booking has been successfully created // Closest pros are :</p>

<% if @selected_professionals.present? %>
  <ul>
    <% @selected_professionals.each do |professional| %>
      <li><%= professional.name %> - <%= professional.address %></li>
    <% end %>
  </ul>
<% else %>
  <p>No nearest professionals found.</p>
<% end %>

app/views/home/index.html.erb
<h1 class="mb-5">Custom Booking</h1>
<%= simple_form_for :booking, url: bookings_path, method: :post do |f| %>
  <%= f.input :prestation_id, as: :select, collection: @prestations, label_method: :reference, value_method: :id, label: "Select a Prestation", include_blank: "Please select" %>

  <%= f.input :starts_at, label: "Choose a Date", class: 'date', as: :datetime %>
  <%= f.input :address_of_prestation, as: :string %>
  <%= f.input :lat, as: :hidden %>
  <%= f.input :lng, as: :hidden %>
  <%= f.button :submit, "Create Booking Request" %>
<% end %>

<h1 class="mt-5">Existing Booking</h1>
<%= simple_form_for :booking, url: find_pro_bookings_path, method: :post do |f| %>
  <%= f.input :booking_id, as: :select, collection: @existing_bookings, label: "Select an existing Booking", include_blank: "Please select" %>
  <%= f.button :submit, "Find pro for existing booking" %>
<% end %>

<script>
  document.addEventListener('DOMContentLoaded', function() {
    flatpickr('.date');
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WecasaTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/flatpickr@latest"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>